# Generated by Django 5.0.6 on 2024-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentapp', '0002_remove_course_students_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='1JT21IS000', max_length=10),
        ),
    ]
