# Generated by Django 5.0.6 on 2024-06-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='C:\\Users\\kamat\\Documents\\DJangoProjs10\\admininterface'),
        ),
    ]
