# Generated by Django 5.0.6 on 2024-06-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=8)),
                ('coursetitle', models.CharField(max_length=30)),
            ],
            options={
                'db_table_comment': 'Holds info about Courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('regno', models.CharField(max_length=10)),
                ('course', models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='forms.course')),
            ],
            options={
                'db_table_comment': 'Holds info about Students',
            },
        ),
    ]
