# Generated by Django 5.0.6 on 2024-06-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_course_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='course',
            table_comment='Holds info about Courses',
        ),
        migrations.AlterModelTableComment(
            name='student',
            table_comment='Holds info about Students',
        ),
        migrations.AddField(
            model_name='student',
            name='course_code',
            field=models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student2course', to='forms.course'),
        ),
    ]
