# Generated by Django 5.0.6 on 2024-06-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_course_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_code',
            field=models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.course'),
        ),
    ]
