# Generated by Django 5.0.6 on 2024-06-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_student_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_code',
        ),
        migrations.AddField(
            model_name='student',
            name='coursecode',
            field=models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_code', to='forms.course'),
        ),
    ]
