# Generated by Django 5.0.6 on 2024-06-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_student_course_code_student_coursecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coursecode',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_coursecode', models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_coursecode', to='forms.course')),
                ('e_regno', models.ForeignKey(db_comment='Foreign Key to the Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_regno', to='forms.student')),
            ],
        ),
    ]
