# Generated by Django 5.0.6 on 2024-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_student_coursecode_enrollment'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='course',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='student',
            table_comment=None,
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
