# Generated by Django 5.0.6 on 2024-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_course_table_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='coursecode',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
