# Generated by Django 5.0.6 on 2024-06-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_course_id_alter_course_coursecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='e_coursecode',
            new_name='coursecode',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='e_regno',
            new_name='regno',
        ),
    ]
