# Generated by Django 5.0.6 on 2024-06-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_rename_e_coursecode_enrollment_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='coursecode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_coursecode', to='forms.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='regno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_regno', to='forms.student'),
        ),
    ]
