# Generated by Django 5.0.6 on 2024-06-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_enrollment_coursecode_alter_enrollment_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='e_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
